name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release Electron App
    runs-on: windows-latest

    steps:
    - name: Install dependencies for Windows build
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wine64 wine32

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the application
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run build

    - name: List dist directory
      run: ls -al dist

    - name: Upload Release Asset to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: dist/EverySearch-win.zip
        tag: AutoBuild
        token: ${{ secrets.GITHUB_TOKEN }}
        updateOnlyUnreleased: true
        replacesArtifacts: true
