name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release Electron App
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the application
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run build

    - name: Delete existing tag and release (if exists)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete AutoBuild --yes || echo "Release doesn't exist."
        git tag -d AutoBuild || echo "Tag doesn't exist."
        git push origin --delete AutoBuild || echo "Remote tag doesn't exist."

    - name: Upload Release Asset to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: dist/EverySearch-win.zip
        tag: AutoBuild
        token: ${{ secrets.GITHUB_TOKEN }}
        updateOnlyUnreleased: true
        replacesArtifacts: true
